name: CI Pipeline - Save Build Logs

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x scripts/bash.sh

      - name: Run build and save log
        run: |
          mkdir -p build
          bash scripts/bash.sh | tee build/build-log.txt

      - name: Upload log file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build/build-log.txt
